# Generated by Django 4.2.2 on 2023-06-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_order_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.address'),
        ),
    ]
