# Generated by Django 4.2.2 on 2023-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(to='main_app.menu_item'),
        ),
    ]
