# Generated by Django 4.2.2 on 2023-06-14 05:26

import django.core.validators
from django.db import migrations
import main_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_address_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=main_app.fields.PhoneNumberField(default=0, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
